export const ORDER_BUILD_VEHICLE_GET = "VEHICLE_GET";
export const ORDER_BUILD_CUSTOMER_GET = "CUSTOMER_GET";
export const ORDER_BUILD_REQUEST = "ORDER_BUILD_REQUEST";
export const ORDER_BUILD_RESPONSE = "ORDER_BUILD_RESPONSE";
export const ORDER_BUILD_ERROR = "ORDER_BUILD_ERROR";
export const ORDER_BUILD_SUBMITTED = "ORDER_BUILD_SUBMITTED";

export const ORDERS_GET_REQUEST = "ORDERS_GET_REQUEST";
export const ORDERS_GET_RESPONSE = "ORDERS_GET_RESPONSE";
export const ORDERS_ERRORS = "ORDERS_ERRORS";
export const ORDERS_CLEAR_ERRORS = "ORDERS_CLEAR_ERRORS";

export const ORDER_PUT_REQUEST = "ORDER_PUT_REQUEST";
export const ORDER_PUT_RESPONSE = "ORDER_PUT_RESPONSE";

export const VEHICLES_GET_REQUEST = "VEHICLES_GET_REQUEST";
export const VEHICLES_GET_RESPONSE = "VEHICLES_GET_RESPONSE";

export const ORDER_STATES = {
  1: "start",
  2: "complete",
  3: "cancel",
  4: "pause"
};
